# Generated by Django 4.1.1 on 2022-12-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IProductive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('taskPoints', models.PositiveSmallIntegerField()),
                ('dailyTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayTasks', to='IProductive.day')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('hobbyPoints', models.PositiveSmallIntegerField()),
                ('dailyTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayHobbies', to='IProductive.day')),
            ],
        ),
    ]
