# Generated by Django 4.1.1 on 2022-12-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IProductive', '0002_tasks_hobby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
